### ISSUE TITLE
1.7.10 Retro Gradle

### ISSUE THREAD

**Issue by Price-MA-Butta** [RetroGradle/ProgressTracker#10]
Hello, a few of us where wondering if we could pay for a 1.7.10 backport so mods like FarPlaneTwo from 1.12 could be successfully backported. 

Name your price. 

If there are any questions, ask DaPorkchop_#0001
He is the FarPlaneTwo modder. I don't know how any of this works but if he is happy with it I am happy to pay for it.

Thank you.

**Comment by TheCurle** [comment]
Sorry, we are not for hire.
