### ISSUE TITLE
ForgeGradle Asset Separation

### ISSUE THREAD

**Issue by TheCurle** [RetroGradle/ProgressTracker#8]
## What
ForgeGradle 2.2 and ForgeGradle 3 have a slight difference in the way assets are managed.
This being; in 2, assets and code are copied into, and loaded from, separate folders. In 3, they are all copied and loaded into the same folder.

## Why
ForgeGradle 3 was modified slightly to work with the new FML redesign that was added in 1.13, and vice versa.
As such, they mutually expect that mod jars will be unpacked and expanded into a single monolithic folder that is representative of the final structure of the jar on disk.

However, when using ForgeGradle 3 with an FML prior to said redesign, this creates an issue: FML loads the code from one folder, tries to read the resources from the other folder, but... they weren't copied there.

## Fix?
A possible fix is to add a feature to ForgeGradle that mimics the old behaviour - copying resources into a separate output folder that FML is more familiar with.

However, this leads into $issue link TODO

**Comment by AterAnimAvis** [comment]
Fixed by RetroGradle/ForgeGradle#1
